spring:
  datasource:
    url: jdbc:hsqldb:mem:todoappDB
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true