spring:
  datasource:
    url: jdbc:hsqldb:mem:todoappDB
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        SQL: TRACE
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
     hibernate:
       SQL: TRACE
       type: TRACE